//Login.java

package staff.menu;

import config.AppConfig;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

/**
 *
 * @author pasta
 */
public class Login extends javax.swing.JFrame {
    private String token;
    /*
    private int loginAttempts =0;
    private final int MAX_ATTEMPTS = 3; //*can adjust max attempts
    ^IF you want a MAX ATTEMPT login feature*/
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

  
    public Login() {
       
        initComponents();
        reset_label.setVisible(false);
        reset_input.setVisible(false);
        reset_submit_button.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        login_header = new javax.swing.JPanel();
        login_closes = new javax.swing.JButton();
        login_title = new javax.swing.JLabel();
        reset_submit_button = new javax.swing.JButton();
        reset_button = new javax.swing.JButton();
        reset_input = new javax.swing.JTextField();
        reset_label = new javax.swing.JLabel();
        login_username = new javax.swing.JLabel();
        login_username_input = new javax.swing.JTextField();
        login_password_input = new javax.swing.JTextField();
        login_password = new javax.swing.JLabel();
        login_button = new javax.swing.JButton();
        login_alert = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(244, 244, 244));
        jPanel2.setForeground(new java.awt.Color(255, 86, 129));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login_header.setBackground(new java.awt.Color(129, 182, 129));

        login_closes.setBackground(new java.awt.Color(244, 244, 244));
        login_closes.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        login_closes.setForeground(new java.awt.Color(84, 135, 79));
        login_closes.setText("close");
        login_closes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        login_closes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login_closes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_closesActionPerformed(evt);
            }
        });

        login_title.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        login_title.setForeground(new java.awt.Color(255, 255, 255));
        login_title.setText("Staff Login");

        javax.swing.GroupLayout login_headerLayout = new javax.swing.GroupLayout(login_header);
        login_header.setLayout(login_headerLayout);
        login_headerLayout.setHorizontalGroup(
            login_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, login_headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(login_title, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 433, Short.MAX_VALUE)
                .addComponent(login_closes, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        login_headerLayout.setVerticalGroup(
            login_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(login_headerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(login_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login_closes)
                    .addComponent(login_title))
                .addGap(1, 1, 1))
        );

        jPanel2.add(login_header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 30));

        reset_submit_button.setBackground(new java.awt.Color(244, 244, 244));
        reset_submit_button.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        reset_submit_button.setForeground(new java.awt.Color(84, 135, 79));
        reset_submit_button.setText("save new password");
        reset_submit_button.setToolTipText("Go to Menu");
        reset_submit_button.setAlignmentY(0.0F);
        reset_submit_button.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        reset_submit_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reset_submit_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        reset_submit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_submit_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(reset_submit_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 130, 18));

        reset_button.setBackground(new java.awt.Color(244, 244, 244));
        reset_button.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        reset_button.setForeground(new java.awt.Color(84, 135, 79));
        reset_button.setText("reset password");
        reset_button.setToolTipText("Go to Menu");
        reset_button.setAlignmentY(0.0F);
        reset_button.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        reset_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reset_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        reset_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(reset_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 360, 110, 18));

        reset_input.setFont(new java.awt.Font("MS UI Gothic", 0, 12)); // NOI18N
        reset_input.setForeground(new java.awt.Color(86, 96, 69));
        reset_input.setText("-");
        reset_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_inputActionPerformed(evt);
            }
        });
        jPanel2.add(reset_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 250, -1));

        reset_label.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        reset_label.setForeground(new java.awt.Color(84, 135, 79));
        reset_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reset_label.setText("Reset Token （＾∀＾●）ﾉｼ");
        jPanel2.add(reset_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 250, 20));

        login_username.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        login_username.setForeground(new java.awt.Color(84, 135, 79));
        login_username.setText("Username ");
        jPanel2.add(login_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 260, 20));

        login_username_input.setFont(new java.awt.Font("MS UI Gothic", 0, 12)); // NOI18N
        login_username_input.setForeground(new java.awt.Color(86, 96, 69));
        login_username_input.setText("-");
        login_username_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_username_inputActionPerformed(evt);
            }
        });
        jPanel2.add(login_username_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 250, -1));

        login_password_input.setFont(new java.awt.Font("MS UI Gothic", 0, 12)); // NOI18N
        login_password_input.setForeground(new java.awt.Color(86, 96, 69));
        login_password_input.setText("-");
        login_password_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_password_inputActionPerformed(evt);
            }
        });
        jPanel2.add(login_password_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 250, -1));

        login_password.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        login_password.setForeground(new java.awt.Color(84, 135, 79));
        login_password.setText("Password （⊙ｏ⊙）");
        jPanel2.add(login_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 260, 20));

        login_button.setBackground(new java.awt.Color(244, 244, 244));
        login_button.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        login_button.setForeground(new java.awt.Color(84, 135, 79));
        login_button.setText("login");
        login_button.setToolTipText("Go to Menu");
        login_button.setAlignmentY(0.0F);
        login_button.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        login_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        login_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(login_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 72, 18));

        login_alert.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        login_alert.setForeground(new java.awt.Color(204, 0, 0));
        login_alert.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(login_alert, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 247, 230, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_closesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_closesActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_login_closesActionPerformed

    private void login_username_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_username_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_login_username_inputActionPerformed

    private void login_password_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_password_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_login_password_inputActionPerformed

    private void login_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_buttonActionPerformed
        // TODO add your handling code here:
        
        /*
        if(loginAttempts >= MAX_ATTEMPTS){
            login_alert.setText("Too many incorrect attempts.");
            login_button.setEnabled(false);
            return;
        }*/ //**if want to add maximum attempts for log in
        
                String user =login_username_input.getText(),
                pass =login_password_input.getText();
        
      
        
        ReadCSV reader = new ReadCSV();
        String roleOrAlert = reader.readFile(user,pass);
        if (roleOrAlert.equals("course_admin") || roleOrAlert.equals("academic_officer")){
            String[] userData = reader.getUserDetails(user);
            
            String staffID = user;
            String firstName = user;
            String lastName = user;
            String roleDisplayName = roleOrAlert;
            
            if (userData != null) {
                staffID = userData[0];
                firstName = userData[1];
                lastName = userData[2];
            }
            
            if (roleOrAlert.equals("course_admin")) {
                roleDisplayName = "Course Admin";
            } else if (roleOrAlert.equals("academic_officer")) {
                roleDisplayName = "Academic Officer";
            }
            if (roleOrAlert.equals("course_admin")) {
                new staff.menu.AdminHomepage(staffID, firstName, lastName, roleDisplayName).setVisible(true); 
            } else if (roleOrAlert.equals("academic_officer")) {
                new staff.menu.OfficerHomepage(staffID, firstName, lastName, roleDisplayName).setVisible(true);
            }
            dispose();
        } else {
            login_alert.setText(roleOrAlert);
            login_password_input.setText(""); 
        }
    }//GEN-LAST:event_login_buttonActionPerformed

    private void reset_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_buttonActionPerformed
        // TODO add your handling code here
        String reset_user =login_username_input.getText();
        String pattern = "^[A]{1}\\d{3}$";
        String reset_email=null;
        
        if (reset_user.contains("@")){
            reset_email=reset_user;
   
        }
        
        if (reset_user.matches(pattern)){
            reset_email = reset_user; //to fetch user email if user only inputs their ID
            
            boolean found = false;
        List<String[]> allRows = new ArrayList<>();
        
        String alert = "";

        try {
            Scanner scan = new Scanner(new File(AppConfig.CSV_PATH));

            // read header
            if (scan.hasNextLine()) {
                allRows.add(scan.nextLine().split(","));
            }

            while (scan.hasNextLine()) {
                String line = scan.nextLine();
                String[] data = line.split(",");
                allRows.add(data);
            }
            
            scan.close();
          
            for (String[] data : allRows) {
                
                if (data[0].equalsIgnoreCase("StaffID")) continue; //skip header
                if (data.length < 10) continue; // skip invalid rows

                String staffID = data[0];
                String firstName = data[1];
                String lastName = data[2];
                String password = data[3];
                String role = data[4];
                String status = data[5];
                String email = data[6];
                String lastLogin = data[7];
                String lastLogout = data[8];
                String loginStatus = data[9];
                
                //fetch email
                if (reset_user.equalsIgnoreCase(staffID)) {
                    reset_email = data[6];
                    alert = "reset token sent to email.";
                    System.out.println("reset token sent to email ("+reset_email+").");
                }


            }
        }catch (FileNotFoundException e) {
            System.out.println("Error: File not found.");
            e.printStackTrace();
                 
        }catch (IOException e) {
            System.out.println("Error: " + e.getMessage());
            e.printStackTrace();
        }}
        
        //continue email sending here
        reset_label.setVisible(true);
        reset_input.setVisible(true);
        
        token = TokenGenerator.generateToken(); // get token
        
        //sending email
        StringBuilder body = new StringBuilder();
        body.append("Hello,\n\n");
        body.append("You requested a password reset. Please use the token below for the system.\n\n");
        body.append(token).append("\n\n");
        
        body.append("Kindly ignore this message if you did not request for password reset.");

        Email emailService = new Email.EmailImpl();
        emailService.sendText(reset_email, "Password Reset Token", body.toString());
        
        reset_submit_button.setVisible(true);
        
        //now user gets new code and action reset_submit_button is performed
        
       
        

        
   
    }//GEN-LAST:event_reset_buttonActionPerformed

    private void reset_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reset_inputActionPerformed

    private void reset_submit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_submit_buttonActionPerformed
        // TODO add your handling code here:
        String user =login_username_input.getText();
        String password =login_password_input.getText();
        String token_input = reset_input.getText();
        String status= null;
        String email=null;
        
        if (token_input.matches(token)){
            //code to match token here
            UpdateUser reader = new UpdateUser();
        String alert = reader.readFile(user,password,status,email);
        login_alert.setText(alert);

        if (alert.startsWith("success")){
            login_alert.setForeground(new java.awt.Color(84,135,79));
             reset_submit_button.setVisible(false);
        }
        }else{
        login_alert.setText("Incorrect token.");
        }
    }//GEN-LAST:event_reset_submit_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel login_alert;
    private javax.swing.JButton login_button;
    private javax.swing.JButton login_closes;
    private javax.swing.JPanel login_header;
    private javax.swing.JLabel login_password;
    private javax.swing.JTextField login_password_input;
    private javax.swing.JLabel login_title;
    private javax.swing.JLabel login_username;
    private javax.swing.JTextField login_username_input;
    private javax.swing.JButton reset_button;
    private javax.swing.JTextField reset_input;
    private javax.swing.JLabel reset_label;
    private javax.swing.JButton reset_submit_button;
    // End of variables declaration//GEN-END:variables


}
