package staff.menu;
import java.awt.*;

/**
 *
 * @author pasta
 */
public class UserManagementFrame extends javax.swing.JFrame {
    
    private CardLayout cardLayout;
    private javax.swing.JFrame parentFrame;
    
    //for updating/add
    private String staffID;
    private String firstName;
    private String lastName;
    private String role;

    public UserManagementFrame(javax.swing.JFrame parent, String staffID, String firstName,String lastName, String role){
        this.parentFrame = parent;
        
            this.staffID = staffID;
            this.firstName = firstName;
            this.lastName = lastName;
            this.role = role;

        initComponents();
        cardLayout = (CardLayout) CardLayoutPanel.getLayout();
        
        welcome_msg.setText("Welcome " + this.firstName + "!");
        menu_footer1.setText("User " + this.staffID + " || " + this.role);
        menu_footer2.setText("User " + this.staffID + " || " + this.role);
        menu_footer.setText("User " + this.staffID + " || " + this.role);
        
        cardLayout.show(CardLayoutPanel, "card3"); //card3 is MenuPanel
        }
    
    public UserManagementFrame(javax.swing.JFrame parent) {
        this(null, "TestID", "TestFirst", "TestLast", "TestRole");
    }
    
    public UserManagementFrame() {
        this(null);
    }
    
    public void showPanel(String name){
        cardLayout.show(CardLayoutPanel,name);
    }
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UserManagementFrame.class.getName());

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CardLayoutPanel = new javax.swing.JPanel();
        MenuPanel = new javax.swing.JPanel();
        welcome_msg = new javax.swing.JLabel();
        menu_footer1 = new javax.swing.JLabel();
        update_user_button = new javax.swing.JButton();
        add_user_button = new javax.swing.JButton();
        UpdateUserPanel = new javax.swing.JPanel();
        update_header = new javax.swing.JPanel();
        login_closes = new javax.swing.JButton();
        login_title = new javax.swing.JLabel();
        update_username_label = new javax.swing.JLabel();
        update_username_input = new javax.swing.JTextField();
        update_button = new javax.swing.JButton();
        update_alert = new javax.swing.JLabel();
        menu_footer = new javax.swing.JLabel();
        update_status_label = new javax.swing.JLabel();
        update_status_input = new javax.swing.JTextField();
        update_email_input = new javax.swing.JTextField();
        update_email_label = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        AddUserPanel = new javax.swing.JPanel();
        add_header = new javax.swing.JPanel();
        add_header_close = new javax.swing.JButton();
        add_title = new javax.swing.JLabel();
        add_lastName_label = new javax.swing.JLabel();
        add_lastName_input = new javax.swing.JTextField();
        add_password_label = new javax.swing.JLabel();
        add_password_input = new javax.swing.JTextField();
        menu_footer2 = new javax.swing.JLabel();
        add_firstName_input = new javax.swing.JTextField();
        add_firstName = new javax.swing.JLabel();
        add_email_input = new javax.swing.JTextField();
        add_email_label = new javax.swing.JLabel();
        add_role_label = new javax.swing.JLabel();
        add_role_input = new javax.swing.JTextField();
        add_alert = new javax.swing.JLabel();
        add_button = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        menu_logout = new javax.swing.JMenuItem();
        menu_home = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        update_user_item = new javax.swing.JMenuItem();
        add_user_item = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(673, 388));
        getContentPane().setLayout(new java.awt.CardLayout());

        CardLayoutPanel.setLayout(new java.awt.CardLayout());

        welcome_msg.setFont(new java.awt.Font("MS Gothic", 0, 48)); // NOI18N
        welcome_msg.setForeground(new java.awt.Color(84, 135, 79));
        welcome_msg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcome_msg.setText("Welcome " + staffID + " !");

        menu_footer1.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        menu_footer1.setForeground(new java.awt.Color(84, 135, 79));
        menu_footer1.setText("User "+staffID+" || "+role);

        update_user_button.setBackground(new java.awt.Color(244, 244, 244));
        update_user_button.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        update_user_button.setForeground(new java.awt.Color(84, 135, 79));
        update_user_button.setText("Update User");
        update_user_button.setToolTipText("Go to Menu");
        update_user_button.setAlignmentY(0.0F);
        update_user_button.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        update_user_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        update_user_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        update_user_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_user_buttonActionPerformed(evt);
            }
        });

        add_user_button.setBackground(new java.awt.Color(244, 244, 244));
        add_user_button.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        add_user_button.setForeground(new java.awt.Color(84, 135, 79));
        add_user_button.setText("Add User");
        add_user_button.setToolTipText("Go to Menu");
        add_user_button.setAlignmentY(0.0F);
        add_user_button.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add_user_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add_user_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add_user_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_user_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuPanelLayout = new javax.swing.GroupLayout(MenuPanel);
        MenuPanel.setLayout(MenuPanelLayout);
        MenuPanelLayout.setHorizontalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuPanelLayout.createSequentialGroup()
                        .addComponent(welcome_msg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(MenuPanelLayout.createSequentialGroup()
                        .addComponent(menu_footer1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(add_user_button, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(update_user_button, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
        );
        MenuPanelLayout.setVerticalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(welcome_msg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menu_footer1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(update_user_button, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_user_button, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        CardLayoutPanel.add(MenuPanel, "card3");

        UpdateUserPanel.setMaximumSize(null);
        UpdateUserPanel.setMinimumSize(new java.awt.Dimension(673, 365));
        UpdateUserPanel.setPreferredSize(new java.awt.Dimension(673, 365));

        update_header.setBackground(new java.awt.Color(129, 182, 129));

        login_closes.setBackground(new java.awt.Color(244, 244, 244));
        login_closes.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        login_closes.setForeground(new java.awt.Color(84, 135, 79));
        login_closes.setText("back");
        login_closes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        login_closes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login_closes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_closesActionPerformed(evt);
            }
        });

        login_title.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        login_title.setForeground(new java.awt.Color(255, 255, 255));
        login_title.setText("UserUpdate - waaaaaaah");

        javax.swing.GroupLayout update_headerLayout = new javax.swing.GroupLayout(update_header);
        update_header.setLayout(update_headerLayout);
        update_headerLayout.setHorizontalGroup(
            update_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, update_headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(login_title, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 461, Short.MAX_VALUE)
                .addComponent(login_closes, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        update_headerLayout.setVerticalGroup(
            update_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(update_headerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(update_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login_closes)
                    .addComponent(login_title))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        update_username_label.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        update_username_label.setForeground(new java.awt.Color(84, 135, 79));
        update_username_label.setText("Username ");

        update_username_input.setFont(new java.awt.Font("MS UI Gothic", 0, 12)); // NOI18N
        update_username_input.setForeground(new java.awt.Color(86, 96, 69));
        update_username_input.setText("-");
        update_username_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_username_inputActionPerformed(evt);
            }
        });

        update_button.setBackground(new java.awt.Color(244, 244, 244));
        update_button.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        update_button.setForeground(new java.awt.Color(84, 135, 79));
        update_button.setText("Update");
        update_button.setToolTipText("Go to Menu");
        update_button.setAlignmentY(0.0F);
        update_button.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        update_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        update_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        update_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_buttonActionPerformed(evt);
            }
        });

        update_alert.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        update_alert.setForeground(new java.awt.Color(204, 0, 0));
        update_alert.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        menu_footer.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        menu_footer.setForeground(new java.awt.Color(84, 135, 79));
        menu_footer.setText("User "+staffID+" || "+role);

        update_status_label.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        update_status_label.setForeground(new java.awt.Color(84, 135, 79));
        update_status_label.setText("New Status");

        update_status_input.setFont(new java.awt.Font("MS UI Gothic", 0, 12)); // NOI18N
        update_status_input.setForeground(new java.awt.Color(86, 96, 69));
        update_status_input.setText("-");
        update_status_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_status_inputActionPerformed(evt);
            }
        });

        update_email_input.setFont(new java.awt.Font("MS UI Gothic", 0, 12)); // NOI18N
        update_email_input.setForeground(new java.awt.Color(86, 96, 69));
        update_email_input.setText("-");
        update_email_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_email_inputActionPerformed(evt);
            }
        });

        update_email_label.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        update_email_label.setForeground(new java.awt.Color(84, 135, 79));
        update_email_label.setText("New Email");

        jPanel1.setFocusable(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/charlieharper.jpg"))); // NOI18N
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel2.setAlignmentY(0.0F);
        jLabel2.setIconTextGap(0);
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 350));

        javax.swing.GroupLayout UpdateUserPanelLayout = new javax.swing.GroupLayout(UpdateUserPanel);
        UpdateUserPanel.setLayout(UpdateUserPanelLayout);
        UpdateUserPanelLayout.setHorizontalGroup(
            UpdateUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(update_header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(UpdateUserPanelLayout.createSequentialGroup()
                .addGroup(UpdateUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UpdateUserPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(menu_footer, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UpdateUserPanelLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(UpdateUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(update_status_label, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(update_email_label, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(update_status_input, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(update_username_label, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(update_username_input, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(UpdateUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(update_button, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(update_email_input, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(update_alert, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        UpdateUserPanelLayout.setVerticalGroup(
            UpdateUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateUserPanelLayout.createSequentialGroup()
                .addComponent(update_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(UpdateUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UpdateUserPanelLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(update_username_label, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(update_username_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(update_status_label, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(update_status_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(update_email_label, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(update_email_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(update_alert, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(update_button, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(menu_footer, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        CardLayoutPanel.add(UpdateUserPanel, "card2");

        AddUserPanel.setMinimumSize(new java.awt.Dimension(673, 365));
        AddUserPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add_header.setBackground(new java.awt.Color(129, 182, 129));

        add_header_close.setBackground(new java.awt.Color(244, 244, 244));
        add_header_close.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        add_header_close.setForeground(new java.awt.Color(84, 135, 79));
        add_header_close.setText("back");
        add_header_close.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add_header_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add_header_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_header_closeActionPerformed(evt);
            }
        });

        add_title.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        add_title.setForeground(new java.awt.Color(255, 255, 255));
        add_title.setText("AddUser - Yippeeeeeee");

        javax.swing.GroupLayout add_headerLayout = new javax.swing.GroupLayout(add_header);
        add_header.setLayout(add_headerLayout);
        add_headerLayout.setHorizontalGroup(
            add_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, add_headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(add_title, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(add_header_close, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        add_headerLayout.setVerticalGroup(
            add_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_headerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(add_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_header_close)
                    .addComponent(add_title))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        AddUserPanel.add(add_header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 679, -1));

        add_lastName_label.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        add_lastName_label.setForeground(new java.awt.Color(84, 135, 79));
        add_lastName_label.setText("Last Name");
        AddUserPanel.add(add_lastName_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 200, 20));

        add_lastName_input.setFont(new java.awt.Font("MS UI Gothic", 0, 12)); // NOI18N
        add_lastName_input.setForeground(new java.awt.Color(86, 96, 69));
        add_lastName_input.setText("-");
        add_lastName_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_lastName_inputActionPerformed(evt);
            }
        });
        AddUserPanel.add(add_lastName_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 260, -1));

        add_password_label.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        add_password_label.setForeground(new java.awt.Color(84, 135, 79));
        add_password_label.setText("Password （⊙ｏ⊙）");
        AddUserPanel.add(add_password_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 200, 20));

        add_password_input.setFont(new java.awt.Font("MS UI Gothic", 0, 12)); // NOI18N
        add_password_input.setForeground(new java.awt.Color(86, 96, 69));
        add_password_input.setText("-");
        add_password_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_password_inputActionPerformed(evt);
            }
        });
        AddUserPanel.add(add_password_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 260, -1));

        menu_footer2.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        menu_footer2.setForeground(new java.awt.Color(84, 135, 79));
        menu_footer2.setText("User "+staffID+" || "+role);
        AddUserPanel.add(menu_footer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 336, 425, 25));

        add_firstName_input.setFont(new java.awt.Font("MS UI Gothic", 0, 12)); // NOI18N
        add_firstName_input.setForeground(new java.awt.Color(86, 96, 69));
        add_firstName_input.setText("-");
        add_firstName_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_firstName_inputActionPerformed(evt);
            }
        });
        AddUserPanel.add(add_firstName_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 260, -1));

        add_firstName.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        add_firstName.setForeground(new java.awt.Color(84, 135, 79));
        add_firstName.setText("First Name");
        AddUserPanel.add(add_firstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 200, 20));

        add_email_input.setFont(new java.awt.Font("MS UI Gothic", 0, 12)); // NOI18N
        add_email_input.setForeground(new java.awt.Color(86, 96, 69));
        add_email_input.setText("-");
        add_email_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_email_inputActionPerformed(evt);
            }
        });
        AddUserPanel.add(add_email_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 260, -1));

        add_email_label.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        add_email_label.setForeground(new java.awt.Color(84, 135, 79));
        add_email_label.setText("Email");
        AddUserPanel.add(add_email_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 200, 20));

        add_role_label.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        add_role_label.setForeground(new java.awt.Color(84, 135, 79));
        add_role_label.setText("Role");
        AddUserPanel.add(add_role_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 200, 20));

        add_role_input.setFont(new java.awt.Font("MS UI Gothic", 0, 12)); // NOI18N
        add_role_input.setForeground(new java.awt.Color(86, 96, 69));
        add_role_input.setText("-");
        add_role_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_role_inputActionPerformed(evt);
            }
        });
        AddUserPanel.add(add_role_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 260, -1));

        add_alert.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        add_alert.setForeground(new java.awt.Color(204, 0, 0));
        add_alert.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AddUserPanel.add(add_alert, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 260, 20));

        add_button.setBackground(new java.awt.Color(244, 244, 244));
        add_button.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        add_button.setForeground(new java.awt.Color(84, 135, 79));
        add_button.setText("Add User");
        add_button.setToolTipText("Go to Menu");
        add_button.setAlignmentY(0.0F);
        add_button.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_buttonActionPerformed(evt);
            }
        });
        AddUserPanel.add(add_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 72, 18));

        jPanel2.setFocusable(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/charlieharper2.jpg"))); // NOI18N
        jLabel3.setToolTipText("");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel3.setAlignmentY(0.0F);
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel3.setIconTextGap(0);
        jLabel3.setRequestFocusEnabled(false);
        jLabel3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 340));

        AddUserPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 29, 233, 341));

        CardLayoutPanel.add(AddUserPanel, "card4");

        getContentPane().add(CardLayoutPanel, "card2");

        jMenu3.setText("File");

        menu_logout.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        menu_logout.setForeground(new java.awt.Color(84, 135, 79));
        menu_logout.setText("logout");
        menu_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_logoutActionPerformed(evt);
            }
        });
        jMenu3.add(menu_logout);

        menu_home.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        menu_home.setForeground(new java.awt.Color(84, 135, 79));
        menu_home.setText("home");
        menu_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_homeActionPerformed(evt);
            }
        });
        jMenu3.add(menu_home);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Edit");

        update_user_item.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        update_user_item.setForeground(new java.awt.Color(84, 135, 79));
        update_user_item.setText("update user");
        update_user_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_user_itemActionPerformed(evt);
            }
        });
        jMenu2.add(update_user_item);

        add_user_item.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        add_user_item.setForeground(new java.awt.Color(84, 135, 79));
        add_user_item.setText("add user");
        add_user_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_user_itemActionPerformed(evt);
            }
        });
        jMenu2.add(add_user_item);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_closesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_closesActionPerformed
        if (parentFrame != null) {
            parentFrame.setVisible(true);
        }
        dispose();
    }//GEN-LAST:event_login_closesActionPerformed

    private void update_username_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_username_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_update_username_inputActionPerformed

    private void update_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_buttonActionPerformed
        // TODO add your handling code here:

        String user = update_username_input.getText(),
        newPassword = null,
        newStatus = update_status_input.getText(),
        newEmail =  update_email_input.getText();


        UpdateUser reader = new UpdateUser();
        String alert = reader.readFile(user,newPassword,newStatus,newEmail);
        update_alert.setText(alert);

        if (alert.startsWith("success")){
            update_alert.setForeground(new java.awt.Color(84,135,79));
            //dispose();
        }
    }//GEN-LAST:event_update_buttonActionPerformed

    private void update_status_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_status_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_update_status_inputActionPerformed

    private void update_email_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_email_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_update_email_inputActionPerformed

    private void menu_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_logoutActionPerformed
        // TODO add your handling code here:
        ReadCSV reader = new ReadCSV();

        reader.logoutUser(staffID);

        dispose();
        new Login().setVisible(true);

    }//GEN-LAST:event_menu_logoutActionPerformed

    private void menu_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_homeActionPerformed
        // TODO add your handling code here:
    cardLayout.show(CardLayoutPanel, "card3"); // "card3" = Home

    }//GEN-LAST:event_menu_homeActionPerformed

    private void update_user_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_user_itemActionPerformed
        // TODO add your handling code here:
    cardLayout.show(CardLayoutPanel, "card2"); // "card2" = UpdateUserPanel

    }//GEN-LAST:event_update_user_itemActionPerformed

    private void update_user_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_user_buttonActionPerformed
        // TODO add your handling code here:
        //new UpdateUser(staffID).setVisible(true);
    cardLayout.show(CardLayoutPanel, "card2"); // "card2" = UpdateUserPanel

    }//GEN-LAST:event_update_user_buttonActionPerformed

    private void add_header_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_header_closeActionPerformed
        // TODO add your handling code here:
        if (parentFrame != null) {
            parentFrame.setVisible(true);
        }
        dispose();

    }//GEN-LAST:event_add_header_closeActionPerformed

    private void add_lastName_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_lastName_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_lastName_inputActionPerformed

    private void add_password_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_password_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_password_inputActionPerformed

    private void add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_buttonActionPerformed
        // TODO add your handling code here:
        String newFirstName = add_firstName_input.getText(),
        newLastName = add_lastName_input.getText(),
        newPassword = add_password_input.getText(),
        newEmail =  add_email_input.getText(),
        newRole =  add_role_input.getText();

        AddUser reader = new AddUser();
        String alert = reader.addUser(newFirstName,newLastName,newPassword,newEmail,newRole);
        add_alert.setText(alert);

        if (alert.startsWith("success")){
            add_alert.setForeground(new java.awt.Color(84,135,79));
         
        }else{
            add_alert.setForeground(new java.awt.Color(204,0,0));
        }
        
        
    }//GEN-LAST:event_add_buttonActionPerformed

    private void add_firstName_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_firstName_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_firstName_inputActionPerformed

    private void add_email_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_email_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_email_inputActionPerformed

    private void add_role_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_role_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_role_inputActionPerformed

    private void add_user_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_user_buttonActionPerformed
        // TODO add your handling code here:
         cardLayout.show(CardLayoutPanel, "card4"); // "card4" = AddUserPanel
    }//GEN-LAST:event_add_user_buttonActionPerformed

    private void add_user_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_user_itemActionPerformed
        // TODO add your handling code here:
      cardLayout.show(CardLayoutPanel, "card4"); // "card4" = AddUserPanel

    }//GEN-LAST:event_add_user_itemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
    

       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // Fix: Pass 'null' as the parent frame
                new UserManagementFrame(null, "test", "test", "test", "test").setVisible(true);
            }
        });
        //java.awt.EventQueue.invokeLater(() -> new UserManagementFrame("test","test","test","test").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddUserPanel;
    private javax.swing.JPanel CardLayoutPanel;
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JPanel UpdateUserPanel;
    private javax.swing.JLabel add_alert;
    private javax.swing.JButton add_button;
    private javax.swing.JTextField add_email_input;
    private javax.swing.JLabel add_email_label;
    private javax.swing.JLabel add_firstName;
    private javax.swing.JTextField add_firstName_input;
    private javax.swing.JPanel add_header;
    private javax.swing.JButton add_header_close;
    private javax.swing.JTextField add_lastName_input;
    private javax.swing.JLabel add_lastName_label;
    private javax.swing.JTextField add_password_input;
    private javax.swing.JLabel add_password_label;
    private javax.swing.JTextField add_role_input;
    private javax.swing.JLabel add_role_label;
    private javax.swing.JLabel add_title;
    private javax.swing.JButton add_user_button;
    private javax.swing.JMenuItem add_user_item;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton login_closes;
    private javax.swing.JLabel login_title;
    private javax.swing.JLabel menu_footer;
    private javax.swing.JLabel menu_footer1;
    private javax.swing.JLabel menu_footer2;
    private javax.swing.JMenuItem menu_home;
    private javax.swing.JMenuItem menu_logout;
    private javax.swing.JLabel update_alert;
    private javax.swing.JButton update_button;
    private javax.swing.JTextField update_email_input;
    private javax.swing.JLabel update_email_label;
    private javax.swing.JPanel update_header;
    private javax.swing.JTextField update_status_input;
    private javax.swing.JLabel update_status_label;
    private javax.swing.JButton update_user_button;
    private javax.swing.JMenuItem update_user_item;
    private javax.swing.JTextField update_username_input;
    private javax.swing.JLabel update_username_label;
    private javax.swing.JLabel welcome_msg;
    // End of variables declaration//GEN-END:variables
}
